version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:latest

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Install firebase
          command: npm install -q firebase-tools
      - run:
          name: Build application
          command: npm run build
      - deploy:
          name: Deploy to production
          command: ./node_modules/.bin/firebase deploy --only hosting --token ${FIREBASE_TOKEN}
